import { UIMessage } from 'ai';

/**
 * Custom UI Message type with data parts for book generation
 * 
 * This extends the AI SDK's UIMessage type to include our custom data parts
 * that enable rich, type-safe streaming UI updates.
 */
export type BookUIMessage = UIMessage<
  never, // no custom metadata
  {
    // ========================================================================
    // Data Part Types
    // ========================================================================

    /**
     * Chapter Status - Progressive updates via reconciliation
     * Same ID updates existing part (loading → completed)
     */
    'chapter-status': {
      chapterNumber: number;
      status: 'loading' | 'completed' | 'error';
      progress: number; // 0-100
      title?: string;
      wordCount?: number;
    };

    /**
     * Book Status - Overall generation progress
     * Updated via reconciliation throughout the process
     */
    'book-status': {
      bookId: string;
      status: 'generating' | 'completed' | 'failed';
      progress: number; // 0-100
      currentStep: string;
      error?: string;
    };

    /**
     * Outline Preview - Shows proposed book structure
     * Requires user approval before proceeding
     */
    'outline': {
      chapterCount: number;
      chapters: Array<{
        number: number;
        title: string;
        synopsis?: string;
      }>;
      synopsis: string;
      approved: boolean;
    };

    /**
     * Transient Notification - Ephemeral status updates
     * NOT saved to message history, only available in onData callback
     */
    'notification': {
      message: string;
      level: 'info' | 'warning' | 'error' | 'success';
    };
  }
>;

/**
 * Tool Approval Request
 * Automatically generated by AI SDK for tools with needsApproval: true
 */
export interface ToolApprovalRequest {
  toolCallId: string;
  toolName: string;
  args: Record<string, unknown>;
}

/**
 * Book Generation State
 * Tracks the overall state of the generation process
 */
export interface BookGenerationState {
  isGenerating: boolean;
  currentStep: string;
  progress: number;
  error?: string;
}

